### PR TITLE
Merging in upstream changes to bring us to parity with boxen

### PR DESCRIPTION
**Pull request by sagagliardo-ct**
Upstream changes from boxen/puppet-elasticsearch which got updated 4 days ago to include ES 1.7.1 support.

### CODE REVIEW

**Comment by armyofgnomes** [comment]
lgtm

**Comment by maulin** [comment]
lgtm

**Comment by sagagliardo-ct** [comment]
apparently "closes" in commit messages is case sensitive in commit messages, so manually closing this out.  Implemented.

**Comment by sagagliardo-ct** [comment]
Closing manually forgot a space in "closes #?"

**Pull request closed without merging**
